const templates = {
  delhi: {
    templateId: "delhi",
    title: "Delhi, India",
    destination: "Delhi, India",
    tripType: "City break",
    durationDays: 4,
    budget: 1200,
    summary: "A balanced Delhi itinerary with monuments, markets, food stops, and time to move between Old and New Delhi.",
    promptNotes: "Urban India itinerary with history, food, and practical transfer planning.",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival and easy evening",
        highlights: ["Check in and rest after arrival.", "Take a short local walk near the hotel.", "Keep dinner convenient and simple."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi or app cab",
        notes: "Start gently and avoid a packed first day.",
      },
      {
        day: 2,
        title: "Monuments and city highlights",
        highlights: ["Visit a major historical landmark.", "Plan a lunch break around your sightseeing route.", "Finish with an evening market or monument view."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and walking",
        notes: "This is the strongest day for timed entries and traffic buffers.",
      },
      {
        day: 3,
        title: "Old Delhi and modern neighborhoods",
        highlights: ["Explore the heritage side of the city.", "Add a food-driven lunch stop.", "Spend the afternoon in a calmer district."],
        meals: ["Breakfast", "Street-food lunch", "Dinner"],
        transport: "Metro, taxi, walking",
        notes: "Blend history, food, and lighter evening pacing.",
      },
      {
        day: 4,
        title: "Buffer and departure",
        highlights: ["Use the morning for a final coffee or shopping.", "Pack early and check your transfer time.", "Head to the airport with a buffer."],
        meals: ["Slow breakfast", "Light lunch"],
        transport: "Taxi or pre-booked transfer",
        notes: "Travel home without rushing.",
      },
    ],
  },
  jaipur: {
    templateId: "jaipur",
    title: "Jaipur, India",
    destination: "Jaipur, India",
    tripType: "Heritage trip",
    durationDays: 3,
    budget: 900,
    summary: "A heritage-focused Jaipur itinerary built around forts, palaces, and well-paced city movement.",
    promptNotes: "Colorful Rajasthan itinerary with cultural landmarks and market time.",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival and old city evening",
        highlights: ["Check in near the heritage core.", "Take a first walk through the old city.", "Have dinner at a relaxed local restaurant."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Keep the first day light and photo-friendly.",
      },
      {
        day: 2,
        title: "Forts and palaces",
        highlights: ["Visit the main fort or palace site.", "Leave time for a scenic lunch stop.", "End with a viewpoint or light shopping."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and walking",
        notes: "Pre-book entry tickets where possible.",
      },
      {
        day: 3,
        title: "Markets and craft stops",
        highlights: ["Spend the morning in the bazaars.", "Try a local lunch.", "Leave the afternoon flexible for souvenirs or cafes."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and walking",
        notes: "A flexible final day works well in Jaipur.",
      },
    ],
  },
  goa: {
    templateId: "goa",
    title: "Goa, India",
    destination: "Goa, India",
    tripType: "Beach trip",
    durationDays: 3,
    budget: 1000,
    summary: "A laid-back Goa itinerary with beaches, sunset time, food stops, and a slow coastal rhythm.",
    promptNotes: "Beach-focused itinerary with enough flexibility for relaxation.",
    itineraryDays: [
      {
        day: 1,
        title: "Beach arrival",
        highlights: ["Check in near the coast.", "Rest after travel and enjoy an evening walk.", "Keep dinner close to the stay."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi or scooter",
        notes: "Let the trip slow down from the start.",
      },
      {
        day: 2,
        title: "Coastal highlights",
        highlights: ["Visit the main beach stretch.", "Plan a lunch stop with sea views.", "Finish with sunset and a relaxed dinner."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Scooter or taxi",
        notes: "This is the scenic centerpiece of the trip.",
      },
      {
        day: 3,
        title: "Food and slow travel",
        highlights: ["Try a breakfast cafe or local eatery.", "Leave the day open for one extra beach stop.", "Pack and depart without rush."],
        meals: ["Breakfast", "Lunch"],
        transport: "Taxi",
        notes: "Keep the last day easy and flexible.",
      },
    ],
  },
  kerala: {
    templateId: "kerala",
    title: "Kerala, India",
    destination: "Kerala, India",
    tripType: "Slow travel",
    durationDays: 3,
    budget: 1300,
    summary: "A calm Kerala itinerary built around backwaters, nature, and a slower pace that feels restorative.",
    promptNotes: "Leisure-focused itinerary with water, nature, and local food.",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival and backwater evening",
        highlights: ["Check in and settle near the water or hills.", "Take a light evening walk.", "Have dinner at the stay or nearby."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Keep arrival day relaxed.",
      },
      {
        day: 2,
        title: "Backwaters or tea country",
        highlights: ["Choose a houseboat, lake, or hill-station experience.", "Plan a scenic lunch stop.", "Finish with a calm evening."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and boat",
        notes: "This is the visual and emotional highlight.",
      },
      {
        day: 3,
        title: "Spices, cafes, and departure prep",
        highlights: ["Visit a local market or spice stop.", "Keep the afternoon flexible for coffee or shopping.", "Pack early and transfer calmly."],
        meals: ["Breakfast", "Lunch"],
        transport: "Taxi",
        notes: "Leave room for a slow, practical finish.",
      },
    ],
  },
  udaipur: {
    templateId: "udaipur",
    title: "Udaipur, India",
    destination: "Udaipur, India",
    tripType: "Heritage trip",
    durationDays: 3,
    budget: 950,
    summary: "A scenic Udaipur itinerary centered on lakes, palaces, and easy old-city wandering.",
    promptNotes: "Romantic heritage city itinerary with scenic viewpoints and relaxed movement.",
    itineraryDays: [
      {
        day: 1,
        title: "Lake arrival",
        highlights: ["Check in and enjoy a first lake view.", "Walk the nearby streets at dusk.", "Keep dinner easy and scenic."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Build in time for a beautiful first evening.",
      },
      {
        day: 2,
        title: "Palaces and viewpoints",
        highlights: ["Visit a palace or fort stop.", "Plan a lake-view lunch.", "End with a sunset viewpoint or boat ride."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and boat",
        notes: "This is the strongest sightseeing day.",
      },
      {
        day: 3,
        title: "Old city wandering",
        highlights: ["Explore lanes, cafes, and handicraft spots.", "Keep lunch simple and local.", "Pack with plenty of buffer."],
        meals: ["Breakfast", "Lunch"],
        transport: "Walking and taxi",
        notes: "A gentle final day suits Udaipur well.",
      },
    ],
  },
  varanasi: {
    templateId: "varanasi",
    title: "Varanasi, India",
    destination: "Varanasi, India",
    tripType: "Cultural trip",
    durationDays: 3,
    budget: 850,
    summary: "A soulful Varanasi itinerary focused on the ghats, sunrise rituals, heritage lanes, and slow evening moments.",
    promptNotes: "Cultural itinerary with sunrise, river views, and local walking routes.",
    itineraryDays: [
      {
        day: 1,
        title: "Ghat-side arrival",
        highlights: ["Check in near the river or old city.", "Take a quiet evening walk.", "Have a simple local dinner."],
        meals: ["Lunch", "Dinner"],
        transport: "Auto or taxi",
        notes: "Keep the first day slow and immersive.",
      },
      {
        day: 2,
        title: "Sunrise and river life",
        highlights: ["Start early for sunrise at the ghats.", "Add a boat ride or riverside stop.", "Spend the afternoon resting or cafe hopping."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Boat, walking, taxi",
        notes: "The early morning rhythm is the core of this itinerary.",
      },
      {
        day: 3,
        title: "Heritage lanes and temples",
        highlights: ["Explore the narrow lanes at a relaxed pace.", "Visit a heritage or temple stop.", "Leave room for a calm evening transfer."],
        meals: ["Breakfast", "Lunch"],
        transport: "Walking and auto",
        notes: "Avoid packing too many locations into one day.",
      },
    ],
  },
  leh: {
    templateId: "leh",
    title: "Leh-Ladakh, India",
    destination: "Leh-Ladakh, India",
    tripType: "Adventure trip",
    durationDays: 4,
    budget: 1800,
    summary: "A mountain itinerary with acclimatization, monastery stops, and scenic road time designed for a slower pace.",
    promptNotes: "High-altitude itinerary with rest time, scenic drives, and practical pacing.",
    itineraryDays: [
      {
        day: 1,
        title: "Acclimatize and rest",
        highlights: ["Check in and rest well after arrival.", "Drink water and keep activity light.", "Take a short walk only if you feel good."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Altitude makes a slow first day important.",
      },
      {
        day: 2,
        title: "Monasteries and viewpoints",
        highlights: ["Visit a nearby monastery or cultural stop.", "Add a scenic lunch break.", "Finish with a quiet sunset viewpoint."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Keep the day scenic and not too dense.",
      },
      {
        day: 3,
        title: "High road exploration",
        highlights: ["Choose a major scenic drive or lake stop.", "Keep photography and breaks in the plan.", "Return early enough for a calm evening."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi or SUV",
        notes: "Weather and road time should stay flexible.",
      },
      {
        day: 4,
        title: "Buffer and departure",
        highlights: ["Pack early and rest.", "Keep the morning light.", "Transfer out with plenty of margin."],
        meals: ["Breakfast", "Light lunch"],
        transport: "Transfer",
        notes: "A relaxed finish matters at altitude.",
      },
    ],
  },
  mumbai: {
    templateId: "mumbai",
    title: "Mumbai, India",
    destination: "Mumbai, India",
    tripType: "City trip",
    durationDays: 4,
    budget: 1100,
    summary: "An energetic Mumbai itinerary with city icons, food stops, and a practical travel rhythm.",
    promptNotes: "Busy city itinerary with strong food and landmark stops.",
    itineraryDays: [
      {
        day: 1,
        title: "Arrival and local area",
        highlights: ["Check in and rest after arrival.", "Take a nearby evening walk.", "Keep the first dinner local and simple."],
        meals: ["Lunch", "Dinner"],
        transport: "Taxi",
        notes: "Stay close to the hotel on day one.",
      },
      {
        day: 2,
        title: "City icons and viewpoints",
        highlights: ["Visit a headline landmark.", "Plan a mid-day meal break.", "Watch the city at golden hour."],
        meals: ["Breakfast", "Lunch", "Dinner"],
        transport: "Taxi and walking",
        notes: "Build in traffic time.",
      },
      {
        day: 3,
        title: "Food and neighborhoods",
        highlights: ["Make food a priority.", "Use the afternoon for a second district.", "Keep the evening flexible."],
        meals: ["Breakfast", "Street food or lunch", "Dinner"],
        transport: "Taxi",
        notes: "This is the most flexible and fun day.",
      },
      {
        day: 4,
        title: "Departure buffer",
        highlights: ["Pack early.", "Have a final coffee stop.", "Leave enough margin for transfer."],
        meals: ["Breakfast", "Light lunch"],
        transport: "Taxi",
        notes: "Travel out without pressure.",
      },
    ],
  },
};

export const getTemplateById = (templateId) => templates[templateId] || null;

export const getAllTemplates = () => Object.values(templates);
